name: Test Workflow
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.1

      - name: Maven test
        run: mvn test

      - name: Checkstyle test
        run: mvn checkstyle:checkstyle
